# Generated by Django 2.0.6 on 2018-06-04 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_auto_20180604_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='description',
        ),
    ]
